### ISSUE TITLE
I'm unable to set `top` or `left` values via the style prop mentioned in the docs.

### ISSUE THREAD

**Issue by snehjogani** [Polyconseil/react-bubble#1]
```
style: {
  container: {
    top: 10,
    borderRadius: '4px',
  },
  arrow: {
    left: {
      borderRightColor: '#2472a6',
    },
    right: {
      borderTopColor: '#2472a6',
    },
  },
  bar: {
    width: '30px',
    backgroundColor: '#2472a6',
    borderTopLeftRadius: '4px',
    borderBottomLeftRadius: '4px',
  }
}
```
all the props apart from top are overridden.

**Comment by lorenzorande** [comment]
Hello Sneh,

`style.container.top` is actually the only prop that is ignored by react-bubble, as it is overridden to position the bubble vertically. I have updated the README to reflect this.

I could not reproduce your problem, could you provide a simple example on a website like codesandbox ?
Here is my attempt to reproduce, with the style exaggerated : https://codesandbox.io/s/232njozlrp
